const express = require("express")
const router = express.Router()
const adminLoginController = require("../controllers/admin.controllers/adminLoginController.js")
const userManagmentController = require("../controllers/admin.controllers/userManagmentController.js")
const itemsPerPageController = require("../controllers/admin.controllers/itemsPerPage.controller.js")
const categoryManagmentController = require("../controllers/admin.controllers/categoryManagmentController.js")
const brandManagmentController = require("../controllers/admin.controllers/brandManagmentController.js")
const productManagmentController = require("../controllers/admin.controllers/productManagmentController.js")
const adminLogoutController = require("../controllers/admin.controllers/adminLogoutController.js")
const searchController = require("../controllers/admin.controllers/searchController.js")
const orderManagementController = require("../controllers/admin.controllers/ordersManagementController.js")
const offerManagementController = require("../controllers/admin.controllers/offerManagementController.js")
const adminAuth = require("../middlewares/admin.auth.js")
const upload = require("../config/multerConfig.js")

router.get("/login",adminLoginController.getAdminLogin)
router.post("/login",adminLoginController.adminLogin)
router.get("/users",userManagmentController.getUsers)
router.get("/block-user",userManagmentController.blockUser)
router.get("/unblock-user",userManagmentController.unblockUser)
router.get("/delete-user",userManagmentController.deleteUser)
router.post("/users",searchController.searchUser)
router.post("/products",searchController.searchProducts)
router.post("/items-per-page",itemsPerPageController.selectedOptionToViewTheList)
router.get("/categories",categoryManagmentController.getCategories)
router.post("/add-category",upload.single("categoryImage"),categoryManagmentController.addCategory)
router.post("/edit-category",upload.single("categoryImage"),categoryManagmentController.editCategory)
router.get("/delete-category",categoryManagmentController.deleteCategory)
router.get("/restore-category",categoryManagmentController.restoreCategory)
router.get("/products",productManagmentController.getProducts)
router.get("/add-product",productManagmentController.getAddProduct)
router.post("/add-product",upload.any(),productManagmentController.addProduct)
router.get("/edit-product",productManagmentController.getEditProduct)
router.post("/edit-product",upload.any(),productManagmentController.editProduct)
router.get("/delete-product",productManagmentController.deleteProduct)
router.get("/restore-product",productManagmentController.restoreProduct)
router.get("/brands",brandManagmentController.getBrand)
router.post("/add-brand",upload.single("brandImage"),brandManagmentController.addBrand)
router.post("/edit-brand",upload.single("brandImage"),brandManagmentController.editBrand)
router.get("/delete-brand",brandManagmentController.deleteBrand)
router.get("/restore-brand",brandManagmentController.restoreBrand)

// Orders Management
router.get("/orders",orderManagementController.getOrders)
router.get("/orders/:id",orderManagementController.getOrderDetailPage)
router.patch("/orders/:id/update-status",orderManagementController.updateStatus)


//Offer Management
router.get("/offers",offerManagementController.getOffers)
router.get("/offers/add-offer",offerManagementController.getAddOffer)
router.get("/offers/edit-offer",offerManagementController.getEditOffer)
router.post("/offers/add-offer",upload.single("bannerImage"),offerManagementController.addOffer)
router.post("/offers/edit-offer",upload.single("bannerImage"),offerManagementController.editOffer)
router.delete("/offers/delete-offer",offerManagementController.deleteOffer)
router.post("/search-products",offerManagementController.searchProducts)
router.get("/search-categories",offerManagementController.searchCategories)


//Logout Admin
router.get("/logout",adminLogoutController.logoutAdmin)

module.exports = router