const express = require("express")
const router = express.Router()
const passport = require("../config/passport.js")
const userAuth = require("../middlewares/user.auth.js")
const userLoginController = require("../controllers/user.controllers/userLogin.controller.js")
const userRegisterController = require("../controllers/user.controllers/userRegister.controller.js")
const userOtpRegisterController = require("../controllers/user.controllers/userOtpForRegisteration.controller.js")
const userOtpNewPassController = require("../controllers/user.controllers/otpForNewPassword.controller.js")
const emailAuthController = require("../controllers/user.controllers/emailAuthForNewPass.controller.js")
const otpNewPassController = require("../controllers/user.controllers/otpForNewPassword.controller.js")
const resetPassController = require("../controllers/user.controllers/resetPassword.controller.js")
const homeController = require("../controllers/user.controllers/home.controller.js")




router.get("/auth/google",passport.authenticate("google",{scope : ["profile","email"]}))
router.get("/auth/google/callback",passport.authenticate("google",{failureRedirect : "/register"}),(req,res) => {
    res.redirect("/")
})
router.get("/login",userAuth.isLogged,userLoginController.getUserLogin)
router.post("/login",userLoginController.userLogin)
router.get("/register",userAuth.isLogged,userRegisterController.getUserRegister)
router.post("/register",userRegisterController.userRegister)
router.get("/otp-verification",userAuth.otpSession,userOtpRegisterController.getUserOtp)
router.post("/otp-verification",userOtpRegisterController.userOtp)
router.get("/",userAuth.checkSession,homeController.getHomepage)
router.get("/shop",userAuth.checkSession,homeController.getShop)
router.post("/shop/filter",userAuth.checkSession,homeController.shopFiltered)
router.get("/product",userAuth.checkSession,homeController.getProductDetail)
router.post("/resend-otp",userOtpRegisterController.resendOtp)
router.post("/resend-otp-for-new-pass",userOtpNewPassController.resendOtpForNewPass)
router.get("/email-auth",emailAuthController.getEmailAuth)
router.post("/email-auth",emailAuthController.emailAuth)
router.get("/otp-verification-for-new-pass",userAuth.otpSession,otpNewPassController.getUserOtpForNewPass)
router.post("/otp-verification-for-new-pass",otpNewPassController.userOtpForNewPass)
router.get("/reset-password",userAuth.otpSession,resetPassController.getResetPassword)
router.post("/reset-password",resetPassController.resetPassword)
router.get("/logout",userAuth.checkSession,homeController.logoutUser)

module.exports = router